### ISSUE TITLE
Remove <html></html> tags in ec3-reduce.js

### ISSUE THREAD

**Issue by ajshiff** [byuitechops/csv-reducer#2]
Cheerio puts `<html>...</html>` tags into code that excludes it, automatically. They aren't supposed to be there. Need to go back in and remove those tags after using cheerio. It looks like it automatically adds `<head></head>` and `<body></body>` tags too. Remove these.

**Comment by meeple142** [comment]
I think there is an option you can give to .html that just gives back there snippet. Look at CSV editor in github

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ajshiff** [comment]
Cheerio has an option that removes this feature. That option is now implemented. 
```
var $ = cheerio.load(htmlstring, {xmlMode: true});
```
